### ISSUE TITLE
on the about survey, "take survey" button does not work 

### ISSUE THREAD

**Issue by Jerome-Clement** [slavefreetrade/libertas_people#42]

**Comment by MichaelKMalak** [comment]
@Jerome-Clement @odhlen @andreasts 
Since on the homepage we check if the survey exists or not/needs to be completed or started, I made the button in the about redirect to the homepage. We can merge this change. However, other options we have:
1. remove the button.
2. make it identical to the homepage. However, this option will be a lot of refactoring and it will take sometime and we will need to test again.

<img src="http://g.recordit.co/2iVFQh3bqx.gif" width=50% height=50%/>
